# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- summer/2022/main
- main

resources:
  repositories:
  - repository: revoltmsgs
    type: git
    name: ReVolt/RevoltMsgs
    trigger:
      - main

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a629a3b8-7119-4fd2-bd21-5302ce2dd42d'
  imageRepository: 'sensor-fusion'
  containerRegistry: 'grdrevolt.azurecr.io'
  dockerfilePath: '$(Pipeline.Workspace)/SensorFusion/Dockerfile'
  tag: 'main'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      path: ./SensorFusion
    - checkout: revoltmsgs
      path: ./RevoltMsgs
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        buildContext: $(Pipeline.Workspace)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)