
azure:
    timeout: 30000
    connection_string: "HostName=REVOLT.azure-devices.net;DeviceId=Boat;SharedAccessKey=R84vSMIdJlEY4UFgljdokSYam4LRkbXGVyXfTGL1/mA=" #Hostname, Device Id & Device Key

modbus:
    ports:
        server: 21000
        gps: 21001
        vru: 21002

udp:
    ais:
        port: 20001
        buffer_size: 512
        rate: 1 # ROS loop rate