tracking:
    lidar:
        parameters:
            gate_probability: 0.99
            maximum_velocity: 8
            detection_probability: 0.9
            M_init: 25
            N_init: 30
            N_terminate: 5
            N_smooth: 1

        ipda:
            use_ipda: false
            survival_probability: 1.0
            init_prob: 0.4
            confirmation_threshold: 0.9
            termination_threshold: 0.1

        topics:
            scan: "/lidar_centroids"
            camera_measurement: "/camera_measurement"
            estimate: "/estimates"

        covariance:
            process:
                target_noise: 0.1
            measurement:
                lidar:
                    type: "cartesian"
                    cartesian: 0.3906
                    range: 100.0
                    bearing: 0.001611

                camera:
                    type: "cartesian"
                    cartesian: 0.5

    radar:
        parameters:
            min_range: 20.0
            max_range: 223.0        # As set in the furuno driver
            scan_intensity_threshold: 6
            start_azimuth: 0.0
            bearing_offset: 0.0
            
        clustering:
            tolerance: 1.5 # Radius [m] around a given point for which we should search for neighbors
            min_size: 50
            max_size: 25000
