/**:
  ros__parameters:
    revolt_ekf:
      # Process noise, The smaller the value, the more you trust your model
      # I can not figure out why this is 12-dimensional and not 15-dimensional, but is taken from:
      # https://github.com/cybergalactic/MSS/blob/master/mssExamples/exINS_AHRS.m
      Q: [20.0, 20.0, 20.0, 5.0, 5.0, 5.0, 10.0, 10.0, 10.0, 5.0, 5.0, 5.0]

      # Measurement noise, the smaller the value, the more you trust your measurements
      # R_vel:  [0.3, 0.3, 0.3] # [v_x, v_y, v_z (m/s)]

      # Time constants for the bias models, chosen based on the matlab example
      T_acc: 100.0 # Eq. 14.195 in Fossen 2nd edition
      T_ars: 60.0 # 14.196 in Fossen 2nd edition

      # Radar -> IMU extrinsic transformation
      l_BR_B: [0.07872, 0.02159, -0.05919] # [x y z]
      q_R_B: [0.9723699204, 0.0, -0.2334453639, 0.0] # [x y z w]

      # ROS2 PARAMETERS
      state_estimate_topic: '/state_estimate/revolt' # Publisher
      imu_topic: '/vectornav_driver_node/imu/data'
      # fix_topic: '/fix'
      # heading_topic: '/heading'
      radar_topic: '/radar/cloud'

      radar_vr_sign: 1        # flip to -1 if your driver uses opposite Doppler sign
      radar_sigma_vr: 0.35    # per-return Doppler noise (m/s), tune 0.25â€“0.6

  