/**:
  ros__parameters:
    revolt_ekf:
      # Process noise, The smaller the value, the more you trust your model
      # I can not figure out why this is 12-dimensional and not 15-dimensional, but is taken from:
      # https://github.com/cybergalactic/MSS/blob/master/mssExamples/exINS_AHRS.m
      Q: [100.0, 100.0, 50.0, 20.0, 1.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

      # Measurement noise, the smaller the value, the more you trust your measurements
      # R_fix:
      # σ_east  = 0.0000196888 [m]
      # σ_north = 0.0000196888 [m]
      # !!! NOTE: This R_fix is not in use anymore, because the GNSS sensor has a inbuilt dynamic covariance matrix, which we are using instead. That GNSS dynamic covariance matrix is superior. It can be found in the /fix topic itself :)
      R_fix:  [0.1, 0.1, 0.1] # [x (m), y (m), z(m)]

      # R_head:
      # σ_heading = 0.074655 [rad]
      R_head: [0.05] # [roll, pitch yaw (rad)]

      # R_vel:
      # σ_velocity_x   = 0.002361 [m/s]
      # σ_velocity_y   = 0.002684 [m/s]
      R_vel:  [0.3, 0.3, 0.3] # [v_x, v_y, v_z (m/s)]

      # Time constants for the bias models, chosen based on the matlab example
      T_acc: 1000.0 # Eq. 14.195 in Fossen 2nd edition
      T_ars: 500.0 # 14.196 in Fossen 2nd edition

      # ROS2 PARAMETERS
      state_estimate_topic: '/state_estimate/revolt'
      imu_topic: '/imu/data'
      fix_topic: '/fix'
      heading_topic: '/heading'
      velocity_topic: '/vel'
